<a href="https://colab.research.google.com/github/Rajeshkeshoju/ml-samples/blob/main/KNN_Iris_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

import pandas as pd

In [ ]:
irisDataCols = load_iris()

In [ ]:
irisData = pd.DataFrame(irisDataCols.data)
irisDataClassLabels = pd.DataFrame(irisDataCols.target)

In [ ]:
columns = ["Sepal Length", "Sepal Width", "Petal Length", "Petal Width"]
classLabels = ["Setosa", "Versicolour", "Virginica"]

In [ ]:
irisData.columns = columns
irisData

     Sepal Length  Sepal Width  Petal Length  Petal Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
irisDataClassLabels.columns = ["Species"]
irisDataClassLabels["Species"] = irisDataClassLabels["Species"].replace(classLabels, [0,1,2])
irisDataClassLabels

     Species
0          0
1          0
2          0
3          0
4          0
..       ...
145        2
146        2
147        2
148        2
149        2

[150 rows x 1 columns]

In [ ]:
x = irisDataCols.data
y = irisDataCols.target

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

knn = KNeighborsClassifier() # default is KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)

# Printing Training data with class label from dataset
tddf=pd.DataFrame(x_train)
tddf.columns = columns
tddf["Species"] = y_train
tddf

     Sepal Length  Sepal Width  Petal Length  Petal Width  Species
0             4.6          3.6           1.0          0.2        0
1             5.7          4.4           1.5          0.4        0
2             6.7          3.1           4.4          1.4        1
3             4.8          3.4           1.6          0.2        0
4             4.4          3.2           1.3          0.2        0
..            ...          ...           ...          ...      ...
115           6.1          2.8           4.0          1.3        1
116           4.9          2.5           4.5          1.7        2
117           5.8          4.0           1.2          0.2        0
118           5.8          2.6           4.0          1.2        1
119           7.1          3.0           5.9          2.1        2

[120 rows x 5 columns]

In [ ]:
# Test data from dataset
# dataset test data classification

test = pd.DataFrame(x_test)
test.columns = columns

# Classifying test data
classLabel = knn.predict(test)
# Adding Species column as resulting class labels from KNN model
test['Species'] = classLabel

# Representing test data and appending result classified labels from KNN model
test['Species'] = test['Species'].replace([0,1,2], classLabels)
test

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

    Sepal Length  Sepal Width  Petal Length  Petal Width      Species
0            6.1          2.8           4.7          1.2  Versicolour
1            5.7          3.8           1.7          0.3       Setosa
2            7.7          2.6           6.9          2.3    Virginica
3            6.0          2.9           4.5          1.5  Versicolour
4            6.8          2.8           4.8          1.4  Versicolour
5            5.4          3.4           1.5          0.4       Setosa
6            5.6          2.9           3.6          1.3  Versicolour
7            6.9          3.1           5.1          2.3    Virginica
8            6.2          2.2           4.5          1.5  Versicolour
9            5.8          2.7           3.9          1.2  Versicolour
10           6.5          3.2           5.1          2.0    Virginica
11           4.8          3.0           1.4          0.1       Setosa
12           5.5          3.5           1.3          0.2       Setosa
13           4.9          3.1           1.5          0.1       Setosa
14           5.1          3.8           1.5          0.3       Setosa
15           6.3          3.3           4.7          1.6  Versicolour
16           6.5          3.0           5.8          2.2    Virginica
17           5.6          2.5           3.9          1.1  Versicolour
18           5.7          2.8           4.5          1.3  Versicolour
19           6.4          2.8           5.6          2.2    Virginica
20           4.7          3.2           1.6          0.2       Setosa
21           6.1          3.0           4.9          1.8    Virginica
22           5.0          3.4           1.6          0.4       Setosa
23           6.4          2.8           5.6          2.1    Virginica
24           7.9          3.8           6.4          2.0    Virginica
25           6.7          3.0           5.2          2.3    Virginica
26           6.7          2.5           5.8          1.8    Virginica
27           6.8          3.2           5.9          2.3    Virginica
28           4.8          3.0           1.4          0.3       Setosa
29           4.8          3.1           1.6          0.2       Setosa

In [ ]:
# Custom test data classification

newTestData = [[1.9, 9.4, 1.6, 7.8], [7.5, 2.3, 5.1, 8.8], [1.2, 3.4, 5.5, 6.6], [9.9, 3.2, 2.3, 4.3], [1.9, 5.6, 3.3, 2.0]]
test = pd.DataFrame(newTestData)
test.columns = columns

# Classifying test data
classLabel = knn.predict(test)
# Adding Species column as resulting class labels from KNN model
test['Species'] = classLabel

# Representing test data and appending result classified labels from KNN model
test['Species'] = test['Species'].replace([0,1,2], classLabels)
test

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

   Sepal Length  Sepal Width  Petal Length  Petal Width      Species
0           1.9          9.4           1.6          7.8       Setosa
1           7.5          2.3           5.1          8.8    Virginica
2           1.2          3.4           5.5          6.6    Virginica
3           9.9          3.2           2.3          4.3  Versicolour
4           1.9          5.6           3.3          2.0       Setosa